version: "3.7"

services:
  traefik:
    image: traefik:v2.9.5
    container_name: traefik
    domainname: clubcelica.es
    restart: always
    networks:
      - wan
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Sets the timezone of the host to the container
      - /etc/localtime:/etc/localtime:ro
      # Mounts docker socket inside the container
      - /var/run/docker.sock:/var/run/docker.sock
      # Traefik configuration files
      - ./config/traefik.yml:/etc/traefik/traefik.yml
      - ./config/dynamic.yml:/etc/traefik/dynamic.yml
      # Traefik plugins
      - ./plugin/geoblock:/plugins-local/src/github.com/PascalMinder/geoblock
      # SSL
      - ./acme:/acme
      # Logs
      - /var/log/traefik:/var/log/traefik
    labels:
      traefik.enable: "false"

networks:
  wan:
    external: true
