tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
      curvePreferences:
        - CurveP521
        - CurveP384
      cipherSuites:
        # TLS 1.2
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        # TLS 1.3
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256

http:
  middlewares:
    compression:
      compress:
        excludedContentTypes:
          - text/event-stream
    security:
      headers:
        accessControlAllowOriginList:
          - "origin-list-or-null"
        addVaryHeader: true
        accessControlMaxAge: 120
        browserXssFilter: true
        contentTypeNosniff: true
        customFrameOptionsValue: "SAMEORIGIN"
        forceSTSHeader: true
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        referrerPolicy: "same-origin"
        permissionsPolicy: "camera 'none'; microphone 'none'"
