tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
      curvePreferences:
        - CurveP521
        - CurveP384
      cipherSuites:
        # TLS 1.2
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        # TLS 1.3
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256

http:
  middlewares:
    crowdsec-bouncer:
      forwardauth:
        address: http://bouncer-traefik:6085/api/v1/forwardAuth
        trustForwardHeader: true
    geoblock:
      plugin:
        geoblock:
          allowLocalRequests: true
          logLocalRequests: false
          logAllowedRequests: false
          logApiRequests: true
          api: "https://get.geojs.io/v1/ip/country/{ip}"
          apiTimeoutMs: 750
          cacheSize: 15
          forceMonthlyUpdate: true
          allowUnknownCountries: false
          unknownCountryApiResponse: "nil"
          countries:
            - ES # Spain
            - FR # France
            - PT # Portugal
            - AR # Argentina
            - BO # Bolivia (Plurinational State of)
            - CL # Chile
            - CO # Colombia
            - CR # Costa Rica
            - DO # Dominican Republic (the)
            - EC # Ecuador
            - SV # El Salvador
            - GT # Guatemala
            - HN # Honduras
            - NI # Nicaragua
            - PA # Panama
            - PY # Paraguay
            - PE # Peru
            - PR # Puerto Rico
            - UY # Uruguay
            - VE # Venezuela (Bolivarian Republic of)
    compression:
      compress:
        excludedContentTypes:
          - text/event-stream
    security:
      headers:
        accessControlAllowOriginList:
          - "origin-list-or-null"
        addVaryHeader: true
        accessControlMaxAge: 120
        browserXssFilter: true
        contentTypeNosniff: true
        customFrameOptionsValue: "SAMEORIGIN"
        forceSTSHeader: true
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        referrerPolicy: "same-origin"
        permissionsPolicy: "camera 'none'; microphone 'none'"
