providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedbydefault: false
    network: wan
  file:
    filename: "/etc/traefik/dynamic.yml"
    watch: true
api:
  dashboard: false
  insecure: false
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
      middlewares:
        - crowdsec-bouncer@file
        - geoblock@file
  websecure:
    address: ":443"
    http:
      middlewares:
        - crowdsec-bouncer@file
        - geoblock@file

log:
  level: INFO
  filePath: "/var/log/traefik/traefik.log"
  format: json

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json
  fields:
    defaultMode: drop
    names:
      StartUTC: keep
      Duration: keep
      OriginStatus: keep
      RequestMethod: keep
      ClientAddr: keep
    headers:
      defaultMode: drop

certificatesResolvers:
  le:
    acme:
      email: "ti@clubcelica.es"
      storage: "/acme/acme.json"
      httpChallenge:
        entryPoint: web

global:
  sendAnonymousUsage: false
  
 experimental:
  localPlugins:
    geoblock:
      moduleName: github.com/PascalMinder/geoblock
